- include/thirdparty/recaptchalib.php
- reCAPTCHA belongs to Google since a long time ago
- it didn't work on https sites
- the decision whether to use SSL should be left to the browser, using a "//www.google.com" URL
> use Google servers for reCAPTCHA and make https sites work

- include/css/inline_image.css
Using width:100%; height:auto; to always scale the thumbs to fit the container and make them better recognizable regardless of their px size.
Not part of this proposal: Maybe also add a basename($image_path) as title attribute to the surrounding <a> tag to hover the filename - sometimes the filename is decisive, especially when different sized of the same image are present in the same directory (?).
> entirely visible thumbs in gallery inline editor

- addons/--Child_Thumbnails/Child_Thumbnails.php
avoid error maximum function nesting level of '250' reached
When page have little bit deeper tree like  - test(childs pages= test1 test2 test3)  test3(childs pages= test4 test5 test6)
and plugin is placed on "test" page and "test3" page.
test page throws error Maximum function nesting level of '250' reached, aborting! in include\tool\Plugins.php   [line] => (integer)132    
so need not to render include secion.
> avoid error maximum function nesting level of '250' reached Update Child_Thumbnails.php

- include/special/special_contact.php
Although we can target the 'sent' message via '.contactform textarea+span', it's clearer to give it a distinct classname
> add 'message_sent' class to span

- include/tool/editing_page.php
...and wrap the links inside a span with white-space:nowrap, so they go into a separate line if there is not enough space.
E.g. needed for german language where "Your changes were saved.   Publish Draft    Discard Draft   Revision History" translates to 
"Ihre Änderungen wurden gespeichert.  Entwurf publizieren   Entwurf verwerfen   Versionsverlauf", which otherwise causes a line break before "Versionsverlauf". This will likely also apply to some other languages.
Proposal for changes to additional.css will follow shortly.
>  add classes for "Publish Draft" and related msg links

- include/tool.php
fixes autoloading for older windows installations
> trim ns character

- include/js/inline_edit/manage_sections.js
trigger event "SectionAdded" in CopySection function 
trigger new event "SectionSorted' in DragStop function
trigger new events "PreviewAdded" and "PreviewRemoved" for section previews
trigger "SectionRemoved" in RemoveSection function.
"*Removed" events will be triggered on the former sections parent, which can be #gpx_content or a wrapper.
With this events, all JS based section types can be initialized (and destroyed if needed) and may also react to changes in the DOM.
> additional events

- include/js/admin.js
... since original event bubbling is blocked with stopPropagation() with this substitute event we can listen to e.g. admin:mouseenter
> trigger substitute event to be used in plugins JS

- include/Page/Edit.php
If a multi-nested Section Combo is defined where a wrapper only contains another wrapper (and no other regular sections), 2 warnings get thrown into the sections list. This is probably not treating the underlying cause but rather symptoms. If so I'm sorry for that -  I currently don't have much time. Anyway, the file changes prevent the warnings.
Sample Code for testing:
```
static function NewSections($links){
global $addonRelativeCode;
$links[] = array( // new section entry
0 => array( // level 0 items array
0 => array( // level 1 item 0: wrapper
0 => array( // level 1 items array
'CustomCombo01-text.gpCol-6',   // pseudo-section-type.section class name(s)
'CustomCombo01-text.gpCol-6',   // pseudo-section-type.section class name(s)
),
1 => 'inner_wrapper_class', 
),
), // end of level 0 …
```
> Multi Nested Combos - fix 2/2

- include/js/inline_edit/inline_editing.js
fires once the editor panel is in the DOM so a plugin can modify the UI
> add a custom JS event when editor is loaded

- include/tool/Output.php
allows plugins and themes to modify/rewrite the content of the html &lt;title&gt; element
> adds new plugin hook 'MetaTitle'

- include/thirdparty/finder/config.js
Enable support for  multiply file selection
If FinderOptionsClient hook use such option
commandsOptions:{
getfile:{
multiple: true,}
> Support for multiply file selection in FinderSelect

- include/css/admin.scss
... if the current page is set to Visibility: Private. 
Users sometimes click this link by accident and only notice that the page is missing when they're logged out.
> ToggleVisibility Admin Link -> red warning color

- README.md
I'm 95% sure that this is a typo since I've never seen a `Prequest` button on Github.
> correcting a typo: Prequest > Request

- include/tool/Output/Css.php
It sets 'compressed' format for SCSS compiler and 
minifies data/_cache/scss_*.css files regardless of theme scss format
> Compress cached files for SCSS

- include/tool/Output/Css.php
It sets 'compressed' format for less_*.css compiled from .less files. So Google PageSpeed Insights will be happy.
> LESS - set 'compressed' format for compiled css

- include/thirdparty/JShrink/Minifier.php
- include/tool/Output/Combine.php
It minifies `combined_*.js` in data/_cache
Add **tedivm/JShrink** Javascript Minifier built in PHP (http://www.tedivm.com) to `/thirdparty`
Call `\JShrink\Minifier::minify()` in `tool/Output/Combine.php `
Result - 10-15% reduced size of `combined_*.js` and 10% of gziped `combined_*.js`
Minification do need some time.
Sorry, I can't estimate additional memory  resources it needs.
But PageSpeed Insights is happy and I am too.
> Minify JS cache

- include/special/Search.php
Fix Deprecated: non-static method gp\special\Search::Gadget() should not be called statically
> Fix non-static method calling

- include/css/admin_finder.scss
Fix for long file names overlapping buttons in preview window header
And, sorry for elFinder again...
before
after
> elFinder: fix for file names overlapping

- addons/Multi Site/SetupSite.php
- include/Page/Rename.php
- include/admin/Notifications.php
- include/js/admin.js
- include/js/main.js
- include/tool.php
- include/tool/Output/Ajax.php
This is a different approach to the same problem fixed with the addition of gprabox in [this commit](31c39ef6f1e7604cd008f4f016787b1552fdf516).
This will add the replaceBox=true option to the AdminBoxC() call whenever a gpabox link is clicked within an admin_box.
> Re: Prevent AJAX replacement effects in Notification box links

- include/admin/Content/Uploaded.php
- include/thirdparty/elFinder/connector.php
Now all file extensions, even files extracted from archives, will be checked.
I also tried to [check files by MIME types](https://github.com/Sestowner/Typesetter/commit/7eb895ae85eff9f713c855cf1da6ea28638b2be0), but I find this changes better.
> elFinder: Improved allowed/denied file extensions check

- include/thirdparty/elFinder/themes/material/css/theme-custom.css
Remove the orange background for the Minimize and Close buttons in dialog title. It is now like in the preview window.
> elFinder: no background on window _ X hover

- include/thirdparty/elFinder/main.custom.js
This is the right way to set dialogContained : true that was done before directly in elfinder.min.js.
As we discussed, I made a [PR](https://github.com/Studio-42/elFinder/pull/3072) to elFinder with my fix. They did not merge it, but made a big [fix](https://github.com/Studio-42/elFinder/commit/9ae38ce2023a23d21afc37d43eb09605f9ff3934). Now it is only in nightly builds and still has some problems.
Maybe  elFinder 2.1.52 will be OK, and we will be able to include it in the TS. So, I decided to prepare for this moment and move our setting for dialog movement limitation from elfinder.min.js to a more proper place.
UPD
I checked this fix with elFinder updated to last nightly build. All work good
> elFinder: preparation for feature releases

- include/css/manage_sections.css
- include/css/manage_sections_compact.css
Before
After
Am I the only one who can not find hovered section in the list in one glance? :)
> Make the outline of a hovered section clearer

- include/tool/Files.php
It's been four years since the PageFile() function was updated to convert sites over to newer files paths and I'd say it's safe to remove the old code.
> Remove old PageFile() code

- include/Base.php
- include/Page/Edit.php
- include/admin/Content/Revisions.php
- include/admin/Layout/Available.php
- include/admin/Layout/Edit.php
- include/admin/Menu.php
- include/admin/Page.php
- include/admin/Tools.php
- include/admin/Tools/Iframe.php
- include/css/admin.scss
- include/css/admin_toolbar.scss
- include/js/admin.js
- include/js/admin/revision.js
- include/js/admin/revisions.js
- include/js/theme_content.js
- include/tool/Output/Combine.php
I think the revision history interface could use an overhaul. Here are my primary complaints about the existing design:
* The list of revisions closes each time a different version is viewed
* Clicking "Previous" and "Next" links in the toolbar don't give the user context of where they're at in the revision history
Here's my new take using a sidebar like the one used for layout editing. What do you all think?
> Revision history redesign

- include/common.php
Throwable was added in php7 which we can use to catch fatal and prevent an entire request from failing. To maintain pre php7 support, we could create our own Throwable and catch Exceptions.
This is an improvement on one of the changes in #340
> Pre php7 throwable

- include/js/ckeditor_config.js
Now the height of the dialogs does not jump when the user changes the tabs.
Note. It is a legal method used in some CKE themes
Before
After
> Make CKE dialogs height same for all tabs

- include/css/manage_sections.css
It expands `<select>` to cover caret sign and to allow to drop down the options instead of checking the box on click.
> Drop-down classes list on caret click

- include/js/inline_edit/gallery_edit_202.js
Juergen. 
It is more a question than a suggestion.
I want to extend gallery editor in my Bootstrap carousel fork. 
To be precise, I want to insert additional checkbox to gallery_edit_202.js gp_editor.
As I see it, section_object  is needed to read the stored editor data.
Am I right? Is this PR permissible, or can I solve my task without it?
As I can see, GalleryEditorTweaks is the only user of gp_editor.editorLoaded() hook. It works fine after the argument has been added to the function.
> Get section_object as argument

- include/js/inline_edit/gallery_edit_202.js
Currently, adding controls in 'editorLoaded' causes a false 'changed' state and prevents the detection of changes in state of added controls. The patch (in fact, lines reorder) fixes this.
> Load hook before original content is determined

- include/admin/Layout.php
Now we see only hex value of layout color
Before
After
> Show layout name in hint

- include/js/inline_edit/inline_editing.js
It is for https://github.com/Typesetter/Typesetter/issues/566
Also.
Should we use
`if( $area.data('draft') == 1 ){`
or change it to
`if( $area.data('draft') ){`
like in all other places?
> Selectiveness for hiding Publish/Dismiss buttons

- include/special/Missing.php
We always show 7 propositions in 'Not Found' page, but not all of them are truly relevant. This patch introduces a threshold for title similarity, but always shows at least one proposition.
Let's try to open page e.g. 'їж'.
Before
After
> Show only relevant propositions in 'Not Found'

- themes/Bootswatch4_Scss/template.php
Without loading the Fontawesome we have such a situation.
> Load fontawesome for admin links icons

- include/special/Missing.php
Now the lowercase() does not work with Unicode symbols at all, e.g. with Cyrillic.
I think, it fails to manage uppercase umlauts as well. Have you noticed?
> Use multibyte lowercase to search similar pages

- include/admin/Content/Revisions.php
It's for https://github.com/Typesetter/Typesetter/issues/560
It uses 'Restore', but we should change it to another label.
> Restore for Current Page

- include/css/theme_content_outer.scss
It's for https://github.com/Typesetter/Typesetter/issues/560#issuecomment-581774573
We can also set visibility to hidden.
> Make non-active Rev.Hist. item edit links disabled

- include/css/manage_sections.css
To prevent this situation when pressing on the clipboard item and dragging mouse
> Prevent text selection starting from Clipboard

- include/css/admin.scss
When I move cursor through menu hovered element changes size.
> Remove jitter in section dropdown edit menu

- include/special/Map.php
Google does not like URL without http:// in site map
Thus 
Before
After
> fix missed protocol in Site_Map?xml
