Typesetter/Typesetter

addons/--Simple_Blog/SimpleBlog.php
CSS class names to discern between single post and post list rendering. Usable for image handling, heading sizes, ...
=> add 'post_list_item' or 'single_post_item' classes

addons/--Simple_Blog/SimpleBlog.php
'blog_home' and 'blog_post_new'
=> CSS classes for easier targeting blog_nav_links

addons/--Simple_Blog/SimpleBlogCommon.php
Helps to style New Post and Edit Post form elements which are currently very hard to target.
=> divs and classes for better CSS targeting

include/special/special_search.php
This will render Bootstrap Pagination (http://getbootstrap.com/components/#pagination) in Bootstrap based themes.
For other themes it would need sth. like …
ul.search_nav_bottom { list-style:none; }
ul.search_nav_bottom li { display:inline; margin-right:0.5em; }
… e.g. in additional.css
=> search_nav_bottom p -> ul, add class pagination

include/thirdparty/js/jquery_cookie.js
I updated jQuery Cookie Plugin to the latest version [1.4.1](https://github.com/carhartl/jquery-cookie)
=> Updated jQuery Cookie Plugin to version 1.4.1

include/tool/editing_page.php
…probably not the final solution but this seems to work by calling NewNestedSection() recursively passing a reconstructed $new_request array to the recursion.
See [this forum post on gpeasy.com](http://www.gpeasy.com/Forum?show=t1985) for how Nested Section Combos could be defined.
edit: oops, there is a typo in the line 
$page->ajaxReplace[] 	= array('PreviewSection','',$output;);
The semicolon after $output is bogus. 
Can I change that in an active pull request?
=> allow adding multi-nested Section Combos

include/tool/editing_page.php
sorry, I forgot to move that line 365 -> 363
=> fix for NewNestedSection()

include/css/additional.css
Button styles for the new links. Quite striking but I think they're necessary – especially for existing users who are used to instant publishing and might overlook it.
=> CSS declarations for Draft + History links in msg

themes/Bootswatch_Scss/template.php
Will make mobile menu work again
=> .navbar-collapse as selector for button data-target

addons/--Bootstrap_Carousel/carousel.js
for folks who to use BS carousel for single image rendering (such as feniweb ;-)
=> hide carousel navigation if only one image is present

include/admin/Configuration.php
Button in admin part to regenerate thumbnails with new size. Also helpfull when people upload images with FTP and no thumbnails were created
as suggested http://www.gpeasy.com/Forum?show=t2011
Translation to langs files add late if change will be accepted.
=> Button for regenerating thumbnails

include/tool/Files.php
=> File paths on windows should have leading slash

include/admin/Menu/Tools.php
see description in the pull request **Custom Combo Label, pt. 1 **
=> Custom Combo Label, pt. 3

include/admin/Content/Extra.php, include/tool/Output.php
Extra Content Visibility depends from page.
This feature I was missing when first time start to work with cms.
This is the first approach, the translation and some ui improvment, I will add if this will be approved.
When extra contet is hardcoded in theme, I think this is "must have" feature.
=> Extra Content Visibility

include/Page/Edit.php
I don't know for what is this part of code. Do we need localization here?
=> Localization 2

include/tool/Editing.php
=> messes with custom plugin-based section labels

include/admin/Layout/Edit.php
IE believe that it is impossible to write <button />
Is he right? :)
=> Autoclosed <button>

include/common.php
Update common.php to include Icelandic language option
=> Include Icelandic language option

include/Page/Edit.php, include/admin/Content/Uploaded.php
Fix PHP Warning:  count(): Parameter must be an array or an object that implements Countable on line 1111
=> Fix PHP Warning

include/Page/Edit.php
Fix PHP Notice:  Undefined index: include_type on line 1811
=> Fix PHP Notice

include/thirdparty/elFinder/connector.php
https://github.com/Typesetter/Typesetter/pull/340#issuecomment-562970014
https://github.com/Typesetter/Typesetter/pull/340#issuecomment-563401171
=> Fix connector.php

include/css/admin.scss
now should works for all major browsers
=> Fix display of #new_section_links > div

include/thirdparty/elFinder/connector.php
now creation of .php3 .php4 .php5 .php7 .phps .php-s .pht .phar  not allowed too
=> Fix pattern for php files

include/js/ckeditor_config.js
Fix from https://github.com/ckeditor/ckeditor4/issues/469#issuecomment-524185244
=> fix. CKEditor refuses to show Paste dialog

include/css/inline_edit.css
=> CKEdior Codemirror: Fix Uncomment button position

include/thirdparty/elFinder/themes/material/css/theme-custom.css
=> elFinder: fix dialog margins and buttons size

include/admin/Tools/Port.php, include/admin/Tools/Status.php, include/tool/FileSystem.php, include/tool/FileSystemFtp.php, phpunit/Admin/StatusTest.php
The issue of writability and a healthy site is more a question of file ownership than file permissions. The new "fix" option recreates unhealthy files with correct ownership.
=> Add "Fix" option to admin status

include/Base.php, include/Page.php, include/Page/Edit.php, include/admin/Layout/Edit.php, include/admin/Settings/Permissions.php
Fixes #413
... and issues that came up in scrutinizer inspections
=> RunCommands() should be public

.easymin/ignore_prefixes, .gitignore
I think this works for everyone's needs
=> "Vendor" ignore configuration

include/js/theme_content_outer.js
Otherwise, a SaveGPUI() request is made for every pixel size change
=> Save the theme editor sidebar at the end of the resize

include/admin/Content/Uploaded.php
=> Delete thumbnail when deleting image from gallery

include/admin/Notifications.php, include/admin/Settings/Preferences.php, include/admin/Tools.php
I kept telling myself I would just make one more change...
* Tabs in dialog instead of previous/next links
* Always sort notifications with highest priority first
* Removed GetDebugInfo() ... was it needed in a plugin?
* Reduced class complexity from [118](https://scrutinizer-ci.com/g/Typesetter/Typesetter/code-structure/master/class/gp%5Cadmin%5CNotifications) to [97](https://scrutinizer-ci.com/g/oyejorge/Typesetter/inspections/da65b801-a3fc-463d-a6d6-86feba6d9dff/code-structure/class/gp%5Cadmin%5CNotifications)
What do you think?
=> Notifications

include/js/inline_edit/gallery_edit_202.js
Decode escape sequence in the file name when create automatic captions
=> decode escape sequence in auto Captions

include/Page/Edit.php, include/admin/Content/Revisions.php, include/admin/Tools.php, include/css/admin.scss, include/css/theme_content_outer.scss, include/js/admin/revisions.js
=> Revision history links

include/Base.php, include/js/admin/revision.js
.. along with cleaning up _RunCommands()
=> Remove editable_area class for #452

.travis.yml, include/Base.php, include/admin/Settings/Permissions.php, include/admin/Settings/Users.php, include/admin/Tools.php, include/common.php, index.php, phpunit/Admin/PermissionsTest.php, phpunit/Admin/UsersTest.php, phpunit/bootstrap.php
* Not running tests on travis ci for php 5.4 or 5.5 any more since they don't pass
* Configure with environment vars
* Permissions and Users updated to use RunScript()
=> Tests for User Permissions and gp_data_type = .json

include/js/main.js, include/tool/Editing.php
Just if you want to try how it will be:)
Now cycling in colorbox is limited to current gallery.
=> Galleries isolated in colorbox

include/admin/Settings/Classes.php
And start presets list from Default (to delete it, if I decided to load BSx preset :)
=> Prevent doubling of classes via append prepend

include/Page/Edit.php, include/tool/Editing.php, include/tool/Output/Extra.php
for #ExtraEditLink & items of IncludeDialog
=> Replace underscores with spaces

include/Page.php, include/admin/Content/Extra.php, include/special/Contact.php, include/tool/Output.php, include/tool/Output/Extra.php, include/tool/Output/Sections.php, phpunit/Admin/ExtraTest.php
These changes make image types editable as extra content
=> Editing for image type. Possible solution for #506

include/admin/Content/Extra.php
Not more than proof of concept
for
https://github.com/Typesetter/Typesetter/issues/530
=> Restore for Extra area

include/admin/Content/Extra.php
Sorry, I have just renamed it and have not tested. 
I hope I have not missed anything.
=> Restore to Dismiss Draft

include/admin/Content/Extra.php, include/css/manage_sections.css, include/js/inline_edit/inline_editing.js, include/js/inline_edit/manage_sections.js, include/tool/Session.php
I think it's a working solution.
But I have done a lot of things blindly and used a lot of duct tape:)
Because many of the solutions in existing code were strictly bound to only one 'publish' button in the house.
Please test it intensively. 
Although you always do that.
UPD
I hope, this is the last step for https://github.com/Typesetter/Typesetter/issues/530
UPD2
~~Now it adds dismiss button and to non-extra section CKE. Need to be fixed.~~ 
Problem is fixed
UPD3
Added vertical margins for buttons in two lines
=> Restore for Extra area step 3

include/css/admin.scss
To prevent appearance of such situation
=> Disable Attribute Value horizontal resizing

include/js/inline_edit/manage_sections.js
Proof of concept
I would like to know what you think about it.
=> Update checkboxes of Available Classes after manual edit

include/Page/Edit.php, include/admin/Content/Extra.php, include/admin/Page.php, include/tool/Output/Extra.php, phpunit/Admin/ExtraTest.php, phpunit/ServerPrepend.php
* display image sections in preview
* save image editing meta correctly
=> More changes for #506

include/tool/Editing.php
Proof of concept
Saves time when searching for highlighted item in a long list.
=> Scroll to used element in File Include list

include/js/inline_edit/inline_editing.js
Fix for fix https://github.com/Typesetter/Typesetter/pull/573/commits/5fb30ba5cac9dcd06aab9e16ff6f73902f1cd478
=> Missed Publish/Dismiss buttons on CKE Text panel

include/tool/Recaptcha.php
Fix for https://github.com/Typesetter/Typesetter/issues/583
=> reCaptcha ignored 'reCaptcha Language' setting

include/admin/Configuration.php
According to https://developers.google.com/recaptcha/docs/language
=> Update reCaptcha Language Codes

include/special/Page.php
Fix for https://github.com/Typesetter/Typesetter/issues/591
=> New AdminLinks style for special pages

addons/--SimilarTitles-Example/SimilarTitles_Example.php
It didn't work for me without such changes
=> Fix for 'Pages not in the Main Menu' example

include/admin/Layout/Text.php
It is for https://github.com/Typesetter/Typesetter/issues/567
=> Fix gpOutput::Area saving to config(customlang)

include/admin/Layout/Text.php
To be like this
But, I am sure my "design" needs some correction.
=>  gpOutput::GetArea editor styling

include/Page/Rename.php
for issue https://github.com/Typesetter/Typesetter/issues/611
=> Fix Auto redirect to page with &

include/special/Map.php
Fix for
https://github.com/Typesetter/Typesetter/issues/639
=> Do not show private pages in xml map

include/js/inline_edit/manage_sections.js
Another PC for https://github.com/Typesetter/Typesetter/issues/636
=> unhighlight last edited section
